<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pardayanlar 1  Pardayanlar</name>
   <tag></tag>
   <elementGuidId>ace9bf5c-578b-463f-a5a8-56c3a886e919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notification']/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c188180-ffef-4742-9ee4-0dec5a85e681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.kitapyurdu.com/kitap/pardayanlar-1--pardayanlar/595981.html</value>
      <webElementGuid>64fc2a74-7e57-4ba6-8e28-25e8e59816b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pardayanlar 1 / Pardayanlar</value>
      <webElementGuid>950bdeee-2c15-48eb-aa4e-9f4d9396ca97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification&quot;)/div[@class=&quot;success&quot;]/a[2]</value>
      <webElementGuid>483c9b09-3d66-4492-a2f8-f6f0262e742f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notification']/div/a[2]</value>
      <webElementGuid>ad2e8f43-cdb9-4073-9695-99ebc030a1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pardayanlar 1 / Pardayanlar')]</value>
      <webElementGuid>b8851998-0be6-43a5-84c4-7ac7e09d0699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Şeker Portakalı (Ciltsiz)'])[1]/following::a[1]</value>
      <webElementGuid>077fc10c-4f31-4e6a-b524-ab1e37caf5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sepetinize'])[1]/preceding::a[1]</value>
      <webElementGuid>e5739c14-c0e6-4bff-89c5-4f537377c577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ana Sayfa'])[1]/preceding::a[2]</value>
      <webElementGuid>ffce8da9-605f-4ac3-b46c-22c9897fbb13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pardayanlar 1 / Pardayanlar']/parent::*</value>
      <webElementGuid>76d17076-00d6-4cdc-ac8b-0bff16874cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.kitapyurdu.com/kitap/pardayanlar-1--pardayanlar/595981.html')]</value>
      <webElementGuid>e149cd55-c55e-4e26-9c3c-489fc771d7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[2]</value>
      <webElementGuid>e0efc169-81be-442b-8586-bd97e8cf1b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.kitapyurdu.com/kitap/pardayanlar-1--pardayanlar/595981.html' and (text() = 'Pardayanlar 1 / Pardayanlar' or . = 'Pardayanlar 1 / Pardayanlar')]</value>
      <webElementGuid>31cb6b02-db9e-4319-8926-7da96f259e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
