<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Teklifi Sepete Ekle</name>
   <tag></tag>
   <elementGuidId>4f67ea24-dba7-48be-b8ab-728dddde1e4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='addCompositeProducts([10139,595981],0,4081200)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.basket-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bddf6dfe-a23b-4b06-a3da-2647ca1cbba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>basket-button</value>
      <webElementGuid>9efd4be5-05c4-4350-908a-e05ec2275e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addCompositeProducts([10139,595981],0,4081200)</value>
      <webElementGuid>92ac99ee-75de-4aa9-be0f-5e63fc53d6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Teklifi Sepete Ekle</value>
      <webElementGuid>66918f20-712d-474f-8beb-69c2a9cdac18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_offer&quot;)/div[@class=&quot;product-offer-inner-frame&quot;]/div[@class=&quot;product-offer&quot;]/div[@class=&quot;offer-action&quot;]/a[@class=&quot;basket-button&quot;]</value>
      <webElementGuid>01b7a361-270b-4ac1-af65-c7e1ae8f1c12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='addCompositeProducts([10139,595981],0,4081200)']</value>
      <webElementGuid>40f8b247-97ed-46ea-bb58-1dab62e511cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product_offer']/div[2]/div/div[3]/a</value>
      <webElementGuid>7bfdef0c-70fb-4712-9a19-f35a43de015c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Teklifi Sepete Ekle')]</value>
      <webElementGuid>ab930c03-9b02-47bd-beb0-c1b8a1659807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='İki Ürün Birlikte:'])[1]/following::a[1]</value>
      <webElementGuid>35f85452-f883-4b8e-a770-59e36ca35272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='İkili Teklif'])[2]/preceding::a[1]</value>
      <webElementGuid>55e6cdf9-8614-45c4-8a9c-fec18db61c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Teklifi Sepete Ekle']/parent::*</value>
      <webElementGuid>fa33a663-bd5f-43b0-b539-106310a5e184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[2]/div/div[3]/a</value>
      <webElementGuid>94c00719-a91a-4e42-99dc-5bde43956967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Teklifi Sepete Ekle' or . = 'Teklifi Sepete Ekle')]</value>
      <webElementGuid>3ae7499d-a9db-45ef-876c-12d7b74f8c86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
