<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c07af456-a2a9-4db6-b910-137e943f8d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Süper Patates 8: Süpermarkette Gizemli Bir Gece&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-603572']/div[3]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6a980183-291d-4e6e-9e2f-9c2b5eb9cc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.kitapyurdu.com/v1/getImage/fn:11498709/wi:100/wh:true</value>
      <webElementGuid>dd1097d9-4159-4068-bda1-40734e830186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Süper Patates 8: Süpermarkette Gizemli Bir Gece</value>
      <webElementGuid>caeb6868-2275-45e3-9cc6-d5b56ed74031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;grid_9&quot;]/div[1]/div[@class=&quot;box no-padding&quot;]/div[2]/ul[@class=&quot;product-grid jcarousel-skin-opencart&quot;]/li[@class=&quot;mg-b-10&quot;]/div[@id=&quot;product-603572&quot;]/div[@class=&quot;image&quot;]/div[@class=&quot;cover&quot;]/a[@class=&quot;pr-img-link&quot;]/img[1]</value>
      <webElementGuid>8de85d60-3411-4bca-95d3-6267a7459c86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-603572']/div[3]/div/a/img</value>
      <webElementGuid>56e3c0f5-1047-4381-acd1-a738330361ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Süper Patates 8: Süpermarkette Gizemli Bir Gece']</value>
      <webElementGuid>f170cf97-91bc-4b4c-afa6-1fc117601a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/img</value>
      <webElementGuid>b5628a32-3813-4418-a686-4b86b46fa603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://img.kitapyurdu.com/v1/getImage/fn:11498709/wi:100/wh:true' and @alt = 'Süper Patates 8: Süpermarkette Gizemli Bir Gece']</value>
      <webElementGuid>8e9b2415-a314-4fcf-9e52-97de8e00dc71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
