<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>43257315-83bf-47d2-9a45-b9193a53f329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-bottom']/div/div[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.logo-text > a > img[alt=&quot;kitapyurdu.com&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ecf7495-e220-4b9a-94ed-2039d632d0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.kitapyurdu.com/v1/getImage/fn:11453388/wh:44a9b399f</value>
      <webElementGuid>e594695f-2939-4054-a74d-d138f0dfc6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>kitapla buluşmanın en kolay yolu!</value>
      <webElementGuid>65ca7a6d-e0fd-4dcb-b698-ec930f88fb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>kitapyurdu.com</value>
      <webElementGuid>43bf5073-2e9b-40af-8033-16fda6d10861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>260</value>
      <webElementGuid>819c5f7d-73d2-4d44-b849-709988e6b8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>74</value>
      <webElementGuid>8cf6b899-6eb1-43aa-b876-ae0b90dcbe37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-bottom&quot;)/div[@class=&quot;container_12 relative&quot;]/div[@class=&quot;logo-text&quot;]/a[1]/img[1]</value>
      <webElementGuid>2bf57127-5a74-4739-8fad-f7c473dbbb41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-bottom']/div/div[2]/a/img</value>
      <webElementGuid>e6d07fca-95d1-4dfe-9e79-071f5065e6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='kitapyurdu.com'])[2]</value>
      <webElementGuid>54080acf-84b9-45ad-88bd-2f148fec8e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>081a51be-df8d-4082-8548-3c4a98c50079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://img.kitapyurdu.com/v1/getImage/fn:11453388/wh:44a9b399f' and @title = 'kitapla buluşmanın en kolay yolu!' and @alt = 'kitapyurdu.com']</value>
      <webElementGuid>e8188085-5048-4ff2-8701-21f90854e051</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
