<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>dc7c2620-28d7-4aae-abf4-fa777c881d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-anasayfa_kategoriler']/div[2]/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cats-wr.swiper-container.swiper-container-initialized.swiper-container-horizontal > div.swiper-wrapper > a.swiper-slide.swiper-slide-active > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6ee85953-c848-4a70-80f9-372879ebade2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.kitapyurdu.com/v1/getImage/fn:11450297/wh:b4254286f</value>
      <webElementGuid>ac04d9d6-cd7d-432e-af9d-17245ed30d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>90f34f6b-1e13-4b7d-8e2c-2cf154b33155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>3ad5b266-5072-4500-b06d-769b330447da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-anasayfa_kategoriler&quot;)/div[@class=&quot;box-content html-display-wr&quot;]/div[@class=&quot;cats-wr swiper-container swiper-container-initialized swiper-container-horizontal&quot;]/div[@class=&quot;swiper-wrapper&quot;]/a[@class=&quot;swiper-slide swiper-slide-active&quot;]/img[1]</value>
      <webElementGuid>e8ab96ac-2207-448f-8ceb-eab21465f80c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-anasayfa_kategoriler']/div[2]/div/div/a/img</value>
      <webElementGuid>8ea00f0b-9c96-4910-9d4f-4ca4ce61fbbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://img.kitapyurdu.com/v1/getImage/fn:11450297/wh:b4254286f')]</value>
      <webElementGuid>f54620df-82fc-4148-b8a9-d92deb0382fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/a/img</value>
      <webElementGuid>37875efe-45dd-413b-922c-0725d4add147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://img.kitapyurdu.com/v1/getImage/fn:11450297/wh:b4254286f']</value>
      <webElementGuid>759f34e7-fcfa-426a-a238-a7c06ec457b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
