<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Puan Katalou_img-lazy-loaded</name>
   <tag></tag>
   <elementGuidId>ced967af-4566-4ccf-a1b5-de4f040aa54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ad-16']/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-lazy-loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8d411251-a26f-4f47-b68a-39ad8b62241b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-lazy-loaded</value>
      <webElementGuid>d15e70d4-94b0-4b9f-99b8-d737ad3fc723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://img.kitapyurdu.com/v1/getImage/fn:11582753/wh:23af4153f</value>
      <webElementGuid>b0117f30-25ed-4dac-b38f-0a86ef1d1b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>690</value>
      <webElementGuid>633f7bf9-729b-4e54-b26c-6d0384e3d5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>baba736f-c27b-454e-a2f6-74b7a1692519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>banner</value>
      <webElementGuid>f0d59719-520a-4952-b0a9-e87d50b3f9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.kitapyurdu.com/v1/getImage/fn:11582753/wh:23af4153f</value>
      <webElementGuid>93d775db-e648-463e-a3d8-518ac1d1a0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ad-16&quot;)/a[1]/img[@class=&quot;img-lazy-loaded&quot;]</value>
      <webElementGuid>1cdaa836-a85f-40b0-bf6e-6fdf86c63762</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ad-16']/a/img</value>
      <webElementGuid>29f44e7b-cd63-4ce6-8631-f4eddc354878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='banner'])[2]</value>
      <webElementGuid>8051b2d9-cf17-4658-8b54-83fd0f7956da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/a/img</value>
      <webElementGuid>2e6b60eb-3c3b-4fd6-ac84-8e45b66e98c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'banner' and @src = 'https://img.kitapyurdu.com/v1/getImage/fn:11582753/wh:23af4153f']</value>
      <webElementGuid>ad2f5026-87da-480e-8293-893d68b55c87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
