<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Akar</name>
   <tag></tag>
   <elementGuidId>f568c198-d0b5-4ba6-a0eb-bc299d94a484</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainNav']/div/ul/li[2]/div[2]/ul/li/div/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.open-menu-ct.literatureMagazine > div.subCategories > ul > li > a.mn-icon.icon-angleRight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>464e64dd-083f-4af1-a07f-50e416df46c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-icon icon-angleRight</value>
      <webElementGuid>b5bf6222-855d-4f35-aec5-cf71414fac34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.kitapyurdu.com/index.php?route=product/publisher_products/all&amp;publisher_id=10255&amp;sort=publish_date&amp;order=DESC</value>
      <webElementGuid>c988e039-3b9c-4770-941c-a4ae06dcfc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aşkar</value>
      <webElementGuid>7f3cbe88-5484-4ab2-9519-c811770d63d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainNav&quot;)/div[@class=&quot;nav-content&quot;]/ul[@class=&quot;lvl1 active&quot;]/li[@class=&quot;magazine has-menu active&quot;]/div[@class=&quot;lvl2 js-magazineCr&quot;]/ul[@class=&quot;js-ajaxCt js-magazineCt&quot;]/li[@class=&quot;has-open-menu selected&quot;]/div[@class=&quot;open-menu-cr&quot;]/div[@class=&quot;open-menu-ct literatureMagazine&quot;]/div[@class=&quot;subCategories&quot;]/ul[1]/li[1]/a[@class=&quot;mn-icon icon-angleRight&quot;]</value>
      <webElementGuid>e9552a88-61bf-416e-b890-9adf28ea8a5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainNav']/div/ul/li[2]/div[2]/ul/li/div/div/div/ul/li/a</value>
      <webElementGuid>196bff62-0779-42fa-b2c7-f0b64fe2f784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Aşkar')]</value>
      <webElementGuid>45e4a8a1-5ca4-4c85-8ed2-3f87c638498e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tüm Dergiler'])[1]/following::a[1]</value>
      <webElementGuid>d645b039-b2de-40d8-ad35-8fddbabba630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Öne Çıkan Edebiyat Dergileri'])[1]/following::a[2]</value>
      <webElementGuid>89b9c13f-0921-4504-a17e-c13a636a9290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baykuş'])[1]/preceding::a[1]</value>
      <webElementGuid>f2085703-e90e-4c51-8886-38c8bc99126b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cins'])[1]/preceding::a[2]</value>
      <webElementGuid>b1d267b2-eb8c-4365-8069-48b1d2586c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aşkar']/parent::*</value>
      <webElementGuid>56de3759-f920-48eb-b1a0-b1d9e34e0df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.kitapyurdu.com/index.php?route=product/publisher_products/all&amp;publisher_id=10255&amp;sort=publish_date&amp;order=DESC')]</value>
      <webElementGuid>b1f7b5b2-b601-4409-9c0a-4c8bba0b1f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/ul/li/div/div/div/ul/li/a</value>
      <webElementGuid>0ff2432c-306b-47b4-9d4b-ac70303ac646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.kitapyurdu.com/index.php?route=product/publisher_products/all&amp;publisher_id=10255&amp;sort=publish_date&amp;order=DESC' and (text() = 'Aşkar' or . = 'Aşkar')]</value>
      <webElementGuid>3ffa21ec-94e7-4b8b-953c-c42a4d8c3751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
