<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ca71c10a-b955-4329-818c-c7fed5e87f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cats-wr.swiper-container.swiper-container-initialized.swiper-container-horizontal > div.swiper-wrapper > a.swiper-slide.swiper-slide-active > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-anasayfa_kategoriler']/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f8259b86-1d0b-455c-85c9-9eb6e41faf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.kitapyurdu.com/v1/getImage/fn:11450297/wh:b4254286f</value>
      <webElementGuid>68177480-eb31-4b7b-a0fa-3d9c73f5d333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>82b9cc53-8fd3-4439-bdf9-b1245e18bc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2642a938-f79c-4750-9646-556d48edd645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-anasayfa_kategoriler&quot;)/div[@class=&quot;box-content html-display-wr&quot;]/div[@class=&quot;cats-wr swiper-container swiper-container-initialized swiper-container-horizontal&quot;]/div[@class=&quot;swiper-wrapper&quot;]/a[@class=&quot;swiper-slide swiper-slide-active&quot;]/img[1]</value>
      <webElementGuid>2dd570cc-9b75-4fc0-8c47-2780b6b8684d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-anasayfa_kategoriler']/div[2]/div/div/a/img</value>
      <webElementGuid>c0a3d311-8e8e-483d-80b0-f47668d8b994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://img.kitapyurdu.com/v1/getImage/fn:11450297/wh:b4254286f')]</value>
      <webElementGuid>f898c9a5-9f34-4126-8176-cd8945938b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/a/img</value>
      <webElementGuid>4713d44e-bdba-458a-bfeb-a4483056b3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://img.kitapyurdu.com/v1/getImage/fn:11450297/wh:b4254286f']</value>
      <webElementGuid>47022f6f-5a4c-45ab-a582-d8dc537e9c91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
