<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ddad684b-4813-40a2-979d-d8069235e4be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-bottom']/div/div[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.logo-text > a > img[alt=&quot;kitapyurdu.com&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ede54106-11ad-4c47-8744-58840a8b9a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.kitapyurdu.com/v1/getImage/fn:11453388/wh:44a9b399f</value>
      <webElementGuid>93c40a45-9106-46de-87bf-8c2fd65a4d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>kitapla buluşmanın en kolay yolu!</value>
      <webElementGuid>238f5a76-02c8-4072-8b9f-2f4abe22d63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>kitapyurdu.com</value>
      <webElementGuid>37ab2d88-d930-4d0a-b553-0efdd520d419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>260</value>
      <webElementGuid>b2df041e-52ce-425f-b75e-65981262c9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>74</value>
      <webElementGuid>fb99a8a9-77e4-4b39-8192-2dbb4d106dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-bottom&quot;)/div[@class=&quot;container_12 relative&quot;]/div[@class=&quot;logo-text&quot;]/a[1]/img[1]</value>
      <webElementGuid>b633dd0c-deed-46c0-a56f-b2e89f8eedcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-bottom']/div/div[2]/a/img</value>
      <webElementGuid>a3c5c8b1-66a4-4eb2-98b6-d44000065a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='kitapyurdu.com'])[2]</value>
      <webElementGuid>1aa9644a-0c9d-42c4-8035-09d8ce0e9b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>11c84fbe-e6d2-47af-86d4-2543fd465628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://img.kitapyurdu.com/v1/getImage/fn:11453388/wh:44a9b399f' and @title = 'kitapla buluşmanın en kolay yolu!' and @alt = 'kitapyurdu.com']</value>
      <webElementGuid>c7300ba4-9dbd-4937-a445-fcf17234659a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
