<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>68ae4dfe-f373-4e9d-bc72-7e161e071e3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-614226']/div[3]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Aşkar Serbest Edebiyat Dergisi Sayı:62 Nisan-Mayıs-Haziran 2022&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>40aa3ac1-c359-42d0-9a9b-d4726460b03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.kitapyurdu.com/v1/getImage/fn:11556870/wi:100/wh:true</value>
      <webElementGuid>a4286e81-2898-4e97-918d-84f2be38c780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Aşkar Serbest Edebiyat Dergisi Sayı:62 Nisan-Mayıs-Haziran 2022</value>
      <webElementGuid>99000bec-1c0f-4424-a2a5-481521e84227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-614226&quot;)/div[@class=&quot;image&quot;]/div[@class=&quot;cover&quot;]/a[@class=&quot;pr-img-link&quot;]/img[1]</value>
      <webElementGuid>6eb8a19c-c68e-4218-b04a-05a9e7bccc1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-614226']/div[3]/div/a/img</value>
      <webElementGuid>214d5740-f24f-4aca-af5a-4e82829b56e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Aşkar Serbest Edebiyat Dergisi Sayı:62 Nisan-Mayıs-Haziran 2022']</value>
      <webElementGuid>f66f116d-2b0a-4508-994f-ba49e82a25de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/img</value>
      <webElementGuid>a354544b-3ee1-4855-b7fe-79b34a125d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://img.kitapyurdu.com/v1/getImage/fn:11556870/wi:100/wh:true' and @alt = 'Aşkar Serbest Edebiyat Dergisi Sayı:62 Nisan-Mayıs-Haziran 2022']</value>
      <webElementGuid>054d8edc-3947-43b1-9615-6edd05e67729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
