<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5d19f0a2-8ea4-4d26-9771-bb8754c77363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.logo-text > a > img[alt=&quot;kitapyurdu.com&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-bottom']/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>295344f4-9040-46a0-9089-8b3b294c9115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.kitapyurdu.com/v1/getImage/fn:11453388/wh:44a9b399f</value>
      <webElementGuid>1c60777d-7bf7-4f57-8c65-36a92742df96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>kitapla buluşmanın en kolay yolu!</value>
      <webElementGuid>a6e1d4b6-b413-436c-916f-90f0adf57bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>kitapyurdu.com</value>
      <webElementGuid>e3db003d-2d69-4fad-8d51-30b371f52f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>260</value>
      <webElementGuid>e87e3e5e-6c64-4479-b22d-c1c68d98bd51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>74</value>
      <webElementGuid>ed5b79a9-8e53-47be-84ad-39f713475834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-bottom&quot;)/div[@class=&quot;container_12 relative&quot;]/div[@class=&quot;logo-text&quot;]/a[1]/img[1]</value>
      <webElementGuid>1347f034-6e6a-4c24-bdfc-3c6d50266cdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-bottom']/div/div[2]/a/img</value>
      <webElementGuid>64c267a3-203a-4a22-999f-8fba61ca6660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='kitapyurdu.com'])[2]</value>
      <webElementGuid>9882b446-e146-4805-9482-2cefc7995539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>d184c74e-e673-457e-a3c2-7cd88ced6d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://img.kitapyurdu.com/v1/getImage/fn:11453388/wh:44a9b399f' and @title = 'kitapla buluşmanın en kolay yolu!' and @alt = 'kitapyurdu.com']</value>
      <webElementGuid>06daf746-56cf-4441-9cff-581422b69025</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
